# Install required packages if not already installed
if (!require("shiny")) install.packages("shiny")
if (!require("shinythemes")) install.packages("shinythemes")
if (!require("dplyr")) install.packages("dplyr")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("plotly")) install.packages("plotly")
if (!require("randomForest")) install.packages("randomForest")
if (!require("caret")) install.packages("caret")
if (!require("readxl")) install.packages("readxl")

# Load required libraries
library(shiny)
library(shinythemes)
library(dplyr)
library(ggplot2)
library(plotly)
library(randomForest)
library(caret)
library(readxl)

# Load and prepare the data
data <- read_excel("C:/Users/hp/Desktop/ML/supply_chain.xlsx")
data <- as.data.frame(data)

# Clean column names to make them syntactically valid
colnames(data) <- make.names(colnames(data))

# Convert categorical variables to factors
data$Product.type <- as.factor(data$Product.type)
data$Location <- as.factor(data$Location)
data$Routes <- as.factor(data$Routes)

# Define the UI
ui <- fluidPage(
  theme = shinytheme("flatly"),
  
  navbarPage(
    title = "Supply Chain Explorer",
    
    tabPanel("Login",
             wellPanel(
               h2("Login"),
               textInput("username", "Username"),
               passwordInput("password", "Password"),
               actionButton("login_button", "Login"),
               br(),
               actionLink("signup_link", "Don't have an account? Sign up")
             )),
    
    tabPanel("Sign Up",
             wellPanel(
               h2("Sign Up"),
               textInput("signup_username", "Username"),
               passwordInput("signup_password", "Password"),
               actionButton("signup_button", "Sign Up"),
               br(),
               actionLink("login_link", "Already have an account? Login")
             )),
    
    tabPanel("Main App",
             conditionalPanel(
               condition = "output.authenticated",
               navbarPage(
                 "SUPPLY CHAIN",
                 tabPanel("Dashboard",
                          sidebarLayout(
                            sidebarPanel(
                              selectInput("product_type", "Select Product Type",
                                          choices = c("All", unique(data$Product.type)),
                                          selected = "All")
                            ),
                            mainPanel(
                              fluidRow(
                                column(6,
                                       plotlyOutput("revenue_boxplot"),
                                       tags$p("Revenue Distribution by Product Type",
                                              class = "text-muted text-center")),
                                column(6,
                                       plotlyOutput("route_doughnut"),
                                       tags$p("Product Type vs Transportation Route",
                                              class = "text-muted text-center"))
                              ),
                              fluidRow(
                                column(6,
                                       plotlyOutput("location_doughnut"),
                                       tags$p("Product Type vs Supplier Location",
                                              class = "text-muted text-center")),
                                column(6,
                                       plotlyOutput("revenue_bar"),
                                       tags$p("Revenue Generated by Product Type",
                                              class = "text-muted text-center"))
                              )
                            )
                          )),
                 tabPanel("Revenue Prediction",
                          sidebarLayout(
                            sidebarPanel(
                              selectInput("product_type_pred", "Product Type",
                                          choices = levels(data$Product.type)),
                              selectInput("location_pred", "Supplier Location",
                                          choices = levels(data$Location)),
                              selectInput("route_pred", "Transportation Route",
                                          choices = levels(data$Routes)),
                              actionButton("predict", "Predict Revenue", 
                                           class = "btn-primary")
                            ),
                            mainPanel(
                              wellPanel(
                                h3("Prediction Results"),
                                verbatimTextOutput("prediction_output")
                              )
                            )
                          ))
               )
             ),
             conditionalPanel(
               condition = "!output.authenticated",
               div(
                 h2("Access Restricted"),
                 p("Please login to access the application.")
               )
             )
    )
  )
)

# Define server logic
server <- function(input, output, session) {
  authenticated <- reactiveVal(FALSE)
  user_database <- reactiveValues(users = list())
  
  observeEvent(input$login_button, {
    username <- input$username
    password <- input$password
    
    if (username %in% names(user_database$users) && 
        user_database$users[[username]] == password) {
      authenticated(TRUE)
      showModal(modalDialog(
        title = "Login Successful",
        "Welcome to the Supply Chain Explorer!",
        easyClose = TRUE,
        footer = NULL
      ))
    } else {
      authenticated(FALSE)
      showModal(modalDialog(
        title = "Login Failed",
        "Invalid username or password.",
        easyClose = TRUE,
        footer = NULL
      ))
    }
  })
  
  observeEvent(input$signup_button, {
    username <- input$signup_username
    password <- input$signup_password
    
    if (!(username %in% names(user_database$users))) {
      user_database$users[[username]] <- password
      authenticated(TRUE)
      showModal(modalDialog(
        title = "Sign Up Successful",
        "Welcome to the Supply Chain Explorer!",
        easyClose = TRUE,
        footer = NULL
      ))
    } else {
      showModal(modalDialog(
        title = "Sign Up Failed",
        "Username already exists.",
        easyClose = TRUE,
        footer = NULL
      ))
    }
  })
  
  observeEvent(input$logout, {
    authenticated(FALSE)
  })
  
  output$authenticated <- reactive({ authenticated() })
  outputOptions(output, "authenticated", suspendWhenHidden = FALSE)
  
  # Reactive filtered data for dashboard
  filtered_data <- reactive({
    if (input$product_type == "All") {
      data
    } else {
      data %>% filter(Product.type == input$product_type)
    }
  })
  
  # Revenue Boxplot
  output$revenue_boxplot <- renderPlotly({
    ggplotly(
      ggplot(filtered_data(), aes(x = Product.type, y = Revenue.generated, fill = Product.type)) +
        geom_boxplot(alpha = 0.7) +
        labs(title = "Revenue Distribution by Product Type",
             x = "Product Type", y = "Revenue Generated") +
        theme_minimal()
    )
  })
  
  # Route Doughnut Chart
  output$route_doughnut <- renderPlotly({
    route_counts <- filtered_data() %>%
      count(Routes) %>%
      mutate(percentage = n / sum(n) * 100)
    
    plot_ly(route_counts, labels = ~Routes, values = ~percentage, type = 'pie', hole = 0.3) %>%
      layout(title = "Product Type vs Transportation Route")
  })
  
  # Location Doughnut Chart
  output$location_doughnut <- renderPlotly({
    location_counts <- filtered_data() %>%
      count(Location) %>%
      mutate(percentage = n / sum(n) * 100)
    
    plot_ly(location_counts, labels = ~Location, values = ~percentage, type = 'pie', hole = 0.3) %>%
      layout(title = "Product Type vs Supplier Location")
  })
  
  # Revenue Bar Chart
  output$revenue_bar <- renderPlotly({
    revenue_data <- filtered_data() %>%
      group_by(Product.type) %>%
      summarise(Revenue = sum(Revenue.generated, na.rm = TRUE))
    
    plot_ly(revenue_data, x = ~Product.type, y = ~Revenue, type = 'bar',
            marker = list(color = '#2ecc71')) %>%
      layout(title = "Revenue Generated by Product Type",
             xaxis = list(title = "Product Type"),
             yaxis = list(title = "Revenue"))
  })
  
  # Train Random Forest Model for Revenue Prediction
  rf_model <- reactive({
    set.seed(123)
    model_data <- data
    train_index <- createDataPartition(model_data$Revenue.generated, p = 0.8, list = FALSE)
    train_data <- model_data[train_index, ]
    
    model <- randomForest(
      Revenue.generated ~ Product.type + Location + Routes,
      data = train_data,
      ntree = 500,
      importance = TRUE
    )
    return(model)
  })
  
  # Revenue Prediction Logic
  prediction <- eventReactive(input$predict, {
    predict_data <- data.frame(
      Product.type = factor(input$product_type_pred, levels = levels(data$Product.type)),
      Location = factor(input$location_pred, levels = levels(data$Location)),
      Routes = factor(input$route_pred, levels = levels(data$Routes))
    )
    
    tryCatch({
      pred <- predict(rf_model(), newdata = predict_data)
      paste("Predicted Revenue: $", format(round(pred, 2), big.mark=","))
    }, error = function(e) {
      paste("Prediction Error:", e$message)
    })
  })
  
  output$prediction_output <- renderText({
    prediction()
  })
}

# Run the Shiny application
shinyApp(ui = ui, server = server)
